name: Pages
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  build-sphinx-docs:
    runs-on: ubuntu-latest
    container: python:3.8.15
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Build Sphinx documentation
        run: bash docs/build_docs.sh

      - name: Install rsync # rsync is needed for the subsequently used action
        run: apt update && apt install -y rsync

      - name: Deploy to GitHub pages
        # Only run this action on the main branch
        # + This action will only update the gh-pages branch if the documentation
        # is affected by the changes that triggered the job
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.4.3
        with:
          BRANCH: gh-pages
          FOLDER: docs/_build/html

      - name: Upload docs artifacts (for testing)
        uses: actions/upload-artifact@v3
        with:
          path: docs/_build/html
