name: Pages
on:
  push:
    branches:
    - main
jobs:
  build-sphinx-docs:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Build Sphinx documentation
        run: bash docs/build_docs.sh

      # rsync is needed for the subsequently used workflow
      - name: Install rsync
        run: apt update && apt install -y rsync
          
      # This workflow will only update the gh-pages branch if the documentation
      # is affected by the changes that triggered the job
      - name: Deploy to GitHub pages
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: docs/_build/html